only_rules:
- block_based_kvo
- class_delegate_protocol
- closing_brace
- collection_alignment
- colon
- comma
- comment_spacing
- compiler_protocol_init
- computed_accessors_order
- contains_over_filter_count
- contains_over_filter_is_empty
- contains_over_first_not_nil
- control_statement
- custom_rules
- cyclomatic_complexity
- deployment_target
- discouraged_direct_init
- duplicate_enum_cases
- duplicate_imports
- duplicated_key_in_dictionary_literal
- dynamic_inline
- empty_collection_literal
- empty_count
- empty_enum_arguments
- empty_parameters
- empty_parentheses_with_trailing_closure
- explicit_init
- file_length
- for_where
- force_cast
- force_try
- function_body_length
- function_parameter_count
- generic_type_name
- identifier_name
- implicit_getter
- inert_defer
- is_disjoint
- large_tuple
- last_where
- leading_whitespace
- legacy_cggeometry_functions
- legacy_constant
- legacy_constructor
- legacy_hashing
- legacy_nsgeometry_functions
- legacy_random
- line_length
- mark
- multiline_function_chains
- multiline_literal_brackets
- multiple_closures_with_trailing_closure
- nesting
- no_fallthrough_only
- no_space_in_method_call
- notification_center_detachment
- nsobject_prefer_isequal
- opening_brace
- operator_whitespace
- orphaned_doc_comment
- overridden_super_call
- private_action
- private_outlet
- private_over_fileprivate
- prohibited_super_call
- protocol_property_accessors_order
- reduce_boolean
- reduce_into
- redundant_discardable_let
- redundant_objc_attribute
- redundant_optional_initialization
- redundant_set_access_control
- redundant_string_enum_value
- redundant_void_return
- return_arrow_whitespace
- self_in_property_initialization
- shorthand_operator
- sorted_first_last
- statement_position
- static_operator
- superfluous_disable_command
- switch_case_alignment
- syntactic_sugar
# - todo
- trailing_newline
- trailing_semicolon
- type_body_length
- type_name
- unneeded_break_in_switch
- unused_capture_list
- unused_closure_parameter
- unused_control_flow_label
- unused_enumerated
- unused_optional_binding
- unused_setter_value
- valid_ibinspectable
- vertical_parameter_alignment
- vertical_parameter_alignment_on_call
- vertical_whitespace
- void_return
- xctfail_message
- unowned_variable_capture

excluded:
- app/*/Carthage
- app/*/Pods
- app/*/vendor
- domain/RoadsideAssistance/RoadsideAssistance/Source/autogenerated
- app/**/secrets.swift
- app/*/DerivedData
- .build
- DerivedData
- .swiftpm
- vendor
- fastlane/actions/implementations/ProjectFactory

force_cast: error
force_try:
    severity: error
block_based_kvo:
  severity: error
class_delegate_protocol:
  severity: error
closing_brace:
  severity: error
collection_alignment:
  severity: error
colon:
  severity: error
comma:
  severity: error
comment_spacing:
  severity: error
compiler_protocol_init:
  severity: error
computed_accessors_order:
  severity: error
contains_over_filter_count:
  severity: error
contains_over_filter_is_empty:
  severity: error
control_statement:
  severity: error
custom_rules:
  severity: error
cyclomatic_complexity:
  severity: error
deployment_target:
  severity: error
discouraged_direct_init:
  severity: error
duplicate_enum_cases:
  severity: error
duplicate_imports:
  severity: error
duplicated_key_in_dictionary_literal:
  severity: error
dynamic_inline:
  severity: error
empty_collection_literal:
  severity: error
empty_count:
  severity: error
empty_enum_arguments:
  severity: error
empty_parameters:
  severity: error
empty_parentheses_with_trailing_closure:
  severity: error
explicit_init:
  severity: error
file_length:
  severity: error
force_cast:
  severity: error
force_try:
  severity: error
function_body_length:
  severity: error
function_parameter_count:
  severity: error
generic_type_name:
  severity: error
implicit_getter:
  severity: error
inert_defer:
  severity: error
is_disjoint:
  severity: error
large_tuple:
  severity: error
last_where:
  severity: error
leading_whitespace:
  severity: error
legacy_cggeometry_functions:
  severity: error
legacy_constant:
  severity: error
legacy_constructor:
  severity: error
legacy_hashing:
  severity: error
legacy_nsgeometry_functions:
  severity: error
legacy_random:
  severity: error
line_length:
  severity: error
mark:
  severity: error
multiline_function_chains:
  severity: error
multiline_literal_brackets:
  severity: error
multiple_closures_with_trailing_closure:
  severity: error
nesting:
  severity: error
no_fallthrough_only:
  severity: error
no_space_in_method_call:
  severity: error
notification_center_detachment:
  severity: error
nsobject_prefer_isequal:
  severity: error
opening_brace:
  severity: error
operator_whitespace:
  severity: error
orphaned_doc_comment:
  severity: error
overridden_super_call:
  severity: error
private_action:
  severity: error
private_outlet:
  severity: error
private_over_fileprivate:
  severity: error
prohibited_super_call:
  severity: error
protocol_property_accessors_order:
  severity: error
redundant_discardable_let:
  severity: error
redundant_objc_attribute:
  severity: error
redundant_optional_initialization:
  severity: error
redundant_set_access_control:
  severity: error
redundant_string_enum_value:
  severity: error
redundant_void_return:
  severity: error
return_arrow_whitespace:
  severity: error
self_in_property_initialization:
  severity: error
shorthand_operator:
  severity: error
sorted_first_last:
  severity: error
statement_position:
  severity: error
static_operator:
  severity: error
superfluous_disable_command:
  severity: error
switch_case_alignment:
  severity: error
syntactic_sugar:
  severity: error
trailing_newline:
  severity: error
trailing_semicolon:
  severity: error
type_body_length:
  severity: error
type_name:
  max_length:
    warning: 60
    error: 60
  severity: error
unneeded_break_in_switch:
  severity: error
unused_capture_list:
  severity: error
unused_closure_parameter:
  severity: error
unused_control_flow_label:
  severity: error
unused_enumerated:
  severity: error
unused_optional_binding:
  severity: error
unused_setter_value:
  severity: error
valid_ibinspectable:
  severity: error
vertical_parameter_alignment:
  severity: error
vertical_parameter_alignment_on_call:
  severity: error
vertical_whitespace:
  severity: error
void_return:
  severity: error
xctfail_message:
  severity: error
reduce_boolean:
  severity: error
for_where:
  severity: error
contains_over_first_not_nil:
  severity: error

identifier_name:
    severity: error
    min_length:
      warning: 3
      error: 3
    max_length: 
      warning: 60
      error: 60
    excluded:
      - id
      - to
      - on
      - km
      - up
      - dc
      - vf
      - am
      - pm
      - QA

line_length:
    warning: 150
    error: 150
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true
function_body_length:
    warning: 300
    error: 300
function_parameter_count:
    warning: 8
    error: 8
type_body_length:
    warning: 500
    error: 500
file_length:
    warning: 800
    error: 800
    ignore_comment_only_lines: true
large_tuple:
    - 3
    - 4
cyclomatic_complexity:
    ignores_case_statements: true
    warning: 15
    error: 25
reporter: "xcode"
nesting:
    type_level: 3
multiple_closures_with_trailing_closure: error
orphaned_doc_comment: error

custom_rules:
  avoid_navCtrl_prefersLargeTitles:
    name: "We shall avoid toggling prefersLargeTitles"
    regex: 'navigationBar\.prefersLargeTitles ='  
    severity: error
    message: 'Thanks for your interest in our prefersLargeTitles. Your code might work fine but others that link to it may see strange effects due to toggled large titles. How else might the desired state be achieved? Thanks for trying. Nothing else? Ah then feel free to use prefersLargeTitles and mute the linter here'
  describe_assert_false:
    name: "Avoid empty assert 'false'"
    regex: 'assert\(false\)'
    message: 'Use assert(false, "description") instead.'
    severity: error
  describe_assertionFailure:
    name: "Avoid empty assertionFailure"
    regex: 'assertionFailure\(\)'
    message: 'Use assertionFailure("description") instead.'
    severity: error
  describe_precondition_false:
    name: "Avoid empty precondition 'false'"
    regex: 'precondition\(false\)'
    message: 'Use precondition(false, "description") instead.'
    severity: error
  describe_preconditionFailure:
    name: "Avoid empty preconditionFailure"
    regex: 'preconditionFailure\(\)'
    message: 'Use preconditionFailure("description") instead.'
    severity: error
  describe_fatalError:
    name: "Avoid empty fatalError"
    regex: 'fatalError\(\)'
    message: 'Use fatalError("description") instead.'
    severity: error
  avoiding_lightweight_assert:
    name: "Avoid lightweight assert"
    regex: 'assert\('
    message: "avoid assert; use XCTAssert (tests) or assertionFailure, precondition, preconditionFailure, or fatalError."
    severity: error
  use_snapshot_typealias:
    name: "Use PAFListSnapshot typealias from PAFUIComponents."
    regex: 'NSDiffableDataSourceSnapshot<PAFListSectionIdentifiable, PAFListModel>'
    severity: error
  use_snapshottestcase:
    name: "Utilize SnapshotTestCase."
    message: "Use `class MySnapshotTests: SnapshotTestCase` so that screenshots are uploaded as artifacts on CI."
    regex: 'class\s+.*Snapshot.*:.*?XCTestCase\s+.*\{.*$'
    severity: error
    excluded: 
      - 'utils/Common/CommonXCTests/SnapshotTestCase/SnapshotTestCase.swift'
  use_networkservice:
    name: "Avoid using URLSession"
    message: "Use `NetworkService` to perform any network request."
    regex: '(URLSession\()|(URLSession\.shared)'
    match_kinds:
      - identifier
    severity: error
    excluded:
      - 'core/Network/Network/Source/Http/ApiClient.swift'
      - 'core/Network/Network/Source/NetworkWebSocketService.swift'
